# Generated by Django 4.1.6 on 2023-02-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0002_category_likes_category_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
